# Generated by Django 6.0.3 on 2026-03-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('melona', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactenquiry',
            name='wedding_date',
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactenquiry',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
